# Generated by Django 6.0 on 2026-01-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verification_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('service_man', 'Service Provider'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
