# Generated by Django 6.0 on 2026-02-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_comparisonpoint_faqcategory_howitworksstep_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityslide',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='review',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='smartfeature',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='techstage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='whychoosepoint',
            name='image_url',
        ),
        migrations.AddField(
            model_name='cityslide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='city_slides/'),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_features/'),
        ),
        migrations.AddField(
            model_name='review',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='review_avatars/'),
        ),
        migrations.AddField(
            model_name='smartfeature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='smart_features/'),
        ),
        migrations.AddField(
            model_name='techstage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tech_stages/'),
        ),
        migrations.AddField(
            model_name='whychoosepoint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='why_choose_points/'),
        ),
    ]
